'use strict';

const path        = require('path');

let config = {
    fontFaceName        : 'foodassembglyphs',
    fontPath            : '../fonts/',
    iconPrefix          : 'icon',
    generatedWarning    : 'This file is generated by foodassembglyphs. Do not edit.',
    pathSrcBase         : path.join(__dirname, 'src'),
    pathSrcSvg          : 'svg/*.svg',
    pathSrcScss         : 'templates/*.scss',
    pathSrcHtmlSpecimen : 'templates/specimen.html',
    pathDestBase        : path.join(__dirname, 'build'),
    pathDestFonts       : 'fonts',
    pathDestScss        : 'scss',
    pathDestHtmlSpecimen: 'specimen',
};

// config.taskPaths.scssExport = path.join(config.taskPaths.scssBuild, '_' + config.fontFaceName + '.scss');

module.exports = config;
