module.exports = {
    fontFaceName    : 'foodassembglyphs',
    fontPath        : '../fonts/',
    iconPrefix      : 'icon',
    generatedWarning: 'This file is generated by foodassembglyphs. Do not edit.',
};
