'use strict'

const path        = require('path');

let config = {
    fontFaceName    : 'foodassembglyphs',
    fontPath        : '../fonts/',
    iconPrefix      : 'icon',
    generatedWarning: 'This file is generated by foodassembglyphs. Do not edit.',
    taskPaths       : {
        svg      : 'svg/*.svg',
        fonts    : 'build/fonts/',
        scssTpl  : 'templates/*.scss',
        scssBuild: 'build/scss',
        htmlTpl  : 'templates/specimen.html',
        htmlBuild: 'build/specimen',
    },
};

config.taskPaths.scssExport = path.join(config.taskPaths.scssBuild, '_' + config.fontFaceName + '.scss');

module.exports = config;
